// <auto-generated />
namespace BruPark.Persistence.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StandaloneLocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StandaloneLocations));
        
        string IMigrationMetadata.Id
        {
            get { return "201601210847328_StandaloneLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
